spring.application.name=network-troubleshooting

#Database configuration Info
spring.datasource.url =${URL}
spring.datasource.username =${USERNAME}
spring.datasource.password =${PASSWORD}


# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true